 services:
   database:
    image: postgres
    restart: always
    #build: ./database
    #volumes:
    #- ".mydb/database:/var/lib/postgresql/data/"
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
    - 5432:5432
    environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=test1234
    networks:
     - common_network
    
   pgamdin:
    image: dpage/pgadmin4:latest
    restart: always
    #build: ./pgadmin
    #volumes:
    #- "D:/mydb/pgadmin:/var/lib/pgadmin"
    environment:
     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
     - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
     - 5050:80
    networks:
     - common_network
     
 networks:
  common_network: